### ISSUE TITLE
Bugfix : areas not displayed after "update" event

### ISSUE THREAD

**Issue by neveldo** [neveldo/jQuery-Mapael#136]
Here is a bug regarding the legend and the "update" event that can be saw on : dataviz_example.html .

Use case : 

1 / Load the dataviz_example.html example
2 / Click on the 'less that 5M' slice to disable all the related countries
3 / Switch to the year 2010.

The China country (this is an example, but the issue affect the other states) is not displayed again while it should.

**Comment by Indigo744** [comment]
The problem appears because of our work on `setLegendElemState`. 
Before: the legend state was always reset to "show", hence no problem
After: the legend state is defined by `setLegendElemState`

Solution: at the beginning of `update`, if the user redefined an area, plot or legend, then reset all legend to show.

**Comment by neveldo** [comment]
Thank you for having fixed it :)
