### ISSUE TITLE
resetAreas

### ISSUE THREAD

**Issue by ghost** [neveldo/jQuery-Mapael#190]
I'm trying to reset the areas of the map with the method resetAreas but does not respond:

$(". Container1").Trigger ('update' [{resetAreas: true}]);

any ideas?

**Comment by Indigo744** [comment]
Dear ToniVeintimilla,

Which version of Mapael are you using? The one downloaded from the website (v. 1.1.0) or the latest one downloaded from the Github master branch (V. 2.x)? This is important because version 2 introduces a breaking change with the update function.

Also, what are you trying to do by "reset the areas of the map"?

**Comment by eslammahgoub** [comment]
I have the same issue when i want to make update for areas or resetAreas but I'm using angular v1.4.x with mapael latest version v.2.x any help
see this [link demo](https://jsbin.com/xufiku/1/edit?html,js,output)

**Comment by Indigo744** [comment]
Closing this now, as no response.

Feel free to reopen issue if needed.
