### ISSUE TITLE
Zoom Event Crashes when  i don't specify Width and Height in the configuration file

### ISSUE THREAD

**Issue by anaszgh** [neveldo/jQuery-Mapael#196]
As far as i understand that Mapael adapts the container's Width/Height if it was not supplied in the configuration file.
The map was displayed fine but when i try to zoom the map disappears and js error appears in the console (see attached image).
and the error occurs because of the following two line being dependent on self.mapConf.width & self.mapConf.height
 panX = Math.min(Math.max(0, zoomOptions.x - (self.mapConf.width / zoomLevel) / 2), (self.mapConf.width - (self.mapConf.width / zoomLevel)));
                panY = Math.min(Math.max(0, zoomOptions.y - (self.mapConf.height / zoomLevel) / 2), (self.mapConf.height - (self.mapConf.height / zoomLevel)));

trying to resolve this issue i hard-coded the width & height that suits me in the onZoomEvent function, but then the panning didn't work.

The second image attached shows how the map looks like if i didn't provide width & height in the configuration file, how can i overcome this issue to make the map adapts the container's dimensions??

![zoom error](https://cloud.githubusercontent.com/assets/4104274/13565001/1b012f24-e456-11e5-8929-f9911c0e1060.png)
![map image](https://cloud.githubusercontent.com/assets/4104274/13565022/3c38f4a6-e456-11e5-884c-d5ce1e276088.png)

**Comment by neveldo** [comment]
Hello,

In the code of the plugin, the self.mapConf variable is the map object which contains the SVG paths, the getCoords() function and ... the original width and the height of the map. These dimensions must be defined in your map file and they must be equals to the dimensions from the SVG file that has been used to build your map, see for instance [this map](https://github.com/neveldo/jQuery-Mapael/blob/master/js/maps/france_departments.js ). The original size of the map is needed by mapael to properly scale the map at initialization, for zooming and panning.  

When a map is displayed on a page, mapael automatically scales its size in order to fit it with its container (if a width have not been set in the instanciation configuration when calling `.mapael({})`).

**Comment by Indigo744** [comment]
@anaszgh any update on this? Do you have a JSFiddle so we can check your code?
