### ISSUE TITLE
can't maintain long lat zoom location with flexible container

### ISSUE THREAD

**Issue by okwme** [neveldo/jQuery-Mapael#197]
hello,

I followed the instructions from issue #76  in order to have a flexible size map. my problem occurs when the ratio of the screen is larger than the ratio of the map and white space appears to the right or below the map instead of centering it or zooming into the long lat coords i provide.

here is a jsfiddle that may describe the problem better. 
(try resizing the preview so it is very wide or very tall)

http://jsfiddle.net/ay8LLndk/2/

**Comment by neveldo** [comment]
Hello,

I think the value for setSize() aren't good, because it break the scale of the map. Here is a fixed JSFiddle example : http://jsfiddle.net/neveldo/mrga03aj/ , you can see that the map stay centered.

If you want the map to fit with the width and the height of the window without preserving the aspect ratio, you have to set preserveAspectRatio to none, here is a JSFiddle example : http://jsfiddle.net/neveldo/6f6bh88c/3/ .

Regarding the zoom trigger (`$(".mapcontainer").trigger("zoom", ...)`, you have to set a level as explained in the doc, here is a JSFiddle example : http://jsfiddle.net/neveldo/ejf9dsL9/

I hope it will help you !

**Comment by billyrennekamp** [comment]
Hi Thanks for your reply
after looking into the aspect ratio trait i realized that actually what i want is the behavior achieved when set to xMidYMid slice. this keeps the coordinates accurate to the actual location on the map.

        paper.canvas.setAttribute('preserveAspectRatio', 'xMidYMid slice');

**Comment by billyrennekamp** [comment]
actually i realize there's still a problem.
the position is now correct on resize, but when the user pans or zooms from this new perspective the map jumps to the wrong scale and position. it seems that the paper.setSize is not preserved, any idea how to set the new dimensions to be kept?

**Comment by Indigo744** [comment]
@okwme do you still have an issue? The new improvements in the zoom function may help you.
