### ISSUE TITLE
A question about selecting one area at a time?

### ISSUE THREAD

**Issue by alexc101** [neveldo/jQuery-Mapael#220]
Hi,

Apologies for raising another issue, but I have been trying to modify my code below so you can only select one area of the map at a time instead of being able to multi-select;

http://plnkr.co/edit/2UAl4Yax99dJAPIDWuTy?p=preview

````
			eventHandlers: {
					click: function(e, id, mapElem) {
						var newData = {
							'areas': {}
						};
						if (mapElem.originalAttrs.fill == "#f4f4e8" && "id[^='department']") {
							newData.areas[id] = {
								attrs: {
									fill: "#0088db"
								}
							};
							$('#' + id).css("visibility", "visible")
						}
						else if (mapElem.originalAttrs.fill == "#0088db" && "id[^='department']") {
							newData.areas[id] = {
								attrs: {
									fill: "#f4f4e8"
								}
							};
							$("#" + id).css("visibility", "hidden")
						}

						$(".mapcontainer").trigger('update', [newData]);

					}
				},
````

I've spent a few hour's trying to come up with a solution of my own, but each time i've not come any closer to solving the issue. 

I've been playing around mostly with .target, .bind and the afterUpdate function but to no avail.

If you could offer any pointers/guidance to set me in the right direction it would be highly appreciated!

Merci,

Alex

**Comment by neveldo** [comment]
Hello,

here is a little example that does it : http://jsfiddle.net/neveldo/wfftgu20/ . It's forked from : http://jsfiddle.net/neveldo/qGwWr/ . The code is quite simple, take a look at the previousSelectedElementId variable that keeps a reference to the previous selected element in order to change its background color if another element is clicked.

I hope it will help you !

**Comment by alexc101** [comment]
Hi,

Oui, c'est parfait!

Merci beaucoup :)
