### ISSUE TITLE
Tooltip position

### ISSUE THREAD

**Issue by reddo** [neveldo/jQuery-Mapael#230]
Is there a way to define the tooltip position in relation to the mouse? Eg. top/right/bottom/left?

**Comment by neveldo** [comment]
Hello @reddo , I don't understand your question because the tooltip position is already set relatively to the mouse position. You can check it on this example for instance : http://jsfiddle.net/neveldo/TUYHN/ . Could you explain more or provide a JSFiddle example of what you want to achieve ?

**Comment by reddo** [comment]
I meant the tooltip  positioned e.g. to the left top of- or simply above the pointer as opposed to always being to the right bottom. Is there some way to define this or it's just automatic?

Sorry, I can't make a JSFiddle example for this.

**Comment by neveldo** [comment]
I now see what you want to get. For now, there is no option to adjust the tooltip position because the top and left offsets are hard-coded within the setTooltip() function : +10px offset from the left, and +20px offset from the top.

You can suggest a pull request that would allow to fine tune to tooltip position by some options. In any case, I will think about it, I think that at least being able to redefine the hard-coded offset should be great . Otherwise, you still can overwrite the setTooltip function in order to define your own behavior.

**Comment by neveldo** [comment]
Done : https://github.com/neveldo/jQuery-Mapael/commit/e01e1aae53854ee61946658adbe489e1202bd4ab

Sample usage (on element options or within defaultArea / defaultPlot objec) : 

    tooltip: {
        offset: {
            left: 100,
            top: 100
        }
    }

**Comment by Indigo744** [comment]
Closed as fixed by v.2.0.0
