### ISSUE TITLE
Top of plot is cut off

### ISSUE THREAD

**Issue by reddo** [neveldo/jQuery-Mapael#233]
If I have a plot on the top side of the map, it gets cut off by the canvas. Is there a way to increase clearance on top of the map to avoid this situation? See here: http://jsfiddle.net/reddo/Lvxkd3fs/9/ and attached screenshot:
![screen shot 2016-05-19 at 14 14 50](https://cloud.githubusercontent.com/assets/1180060/15391818/16902bca-1dcc-11e6-83be-29014631cf55.png)

**Comment by neveldo** [comment]
Hello @reddo ,

I think the proper way should be to edit the map, in order to add some more blank spaces around the USA. 

Take a look at the tutorial : http://www.vincentbroute.fr/mapael/create-map.php .You just have to use [Mapael To SVG tool](http://www.vincentbroute.fr/mapael/mapael-to-svg.php) in order to get a SVG file of the map editable through inscakpe. With Inkscape, you will be able to enlarge the map dimensions easily. The you will just have to convert the SVG file back to the Mapael format with [this tool](http://www.vincentbroute.fr/mapael/svg-to-mapael.php). 

You will also have to copy/paste the getCoords() function and adjust the values of xOffset and yOffset variables.

**Comment by reddo** [comment]
Hi @neveldo,

The mapael to svg too doesn't seem to work. it just gives me a 205 bytes empty file with no extension :|

I've tried renaming it and opening in Adobe Illustrator but it's empty.

**Comment by neveldo** [comment]
Hmm, did you upload the non-minified version of the map ? I have checked with the map you have used in your JSFiddle (https://cdn.rawgit.com/neveldo/jQuery-Mapael/1.1.0/js/maps/usa_states.js), and it seems to work fine.

**Comment by reddo** [comment]
Yes, I tried both minified and unminified ones and neither worked. 

Could you maybe send me a link to the svg version? I'd be terribly grateful if you'd send me the modified js file too, it'd take a lot less time for you to modify it, as I have absolutely no idea what i should do to adjust the coordinates. Adding 10px space all around should do it, but I totally understand if you don't have the time. You're doing an awesome job with this plugin, by the way. Keep up the good work!

**Comment by neveldo** [comment]
Here we go : 

https://gist.github.com/neveldo/1bfccf19dee4f91b2941baddb898e081

I hope it will fit your needs (unfortunately, I will not have so much time to do other custom maps)

**Comment by reddo** [comment]
You are **THE** man! Thank you! I'll give it a try as soon as I get a chance.
