### ISSUE TITLE
Reset all areas to default fill on 'update'

### ISSUE THREAD

**Issue by akashdeepkanojia** [neveldo/jQuery-Mapael#235]
Hi,

Thanks for the awesome plugin. 
I'm using mapael 2.0.0.
It's not an issue just a question. I checked the [documentation](http://www.vincentbroute.fr/mapael/) here, but its still for old version I guess.
Is there any option to reset all areas to default attributes on update call?

Here's a [fiddle](https://jsfiddle.net/akashdeepkanojia/crg1k8zj/) to understand the concept.

In this fiddle, is it possible that when you select one country, the other countries could go back to default ?

Thanks

**Comment by neveldo** [comment]
Hi, 

You're welcome :) . FYI, the updated documentation for Mapael 2.0.0 is avaiable in the 'mapael-documentation' repository (branch 2.0.0-dev) : https://github.com/neveldo/mapael-documentation/tree/2.0.0-dev . (see also here for a direct link to the updated doc page : https://cdn.rawgit.com/neveldo/mapael-documentation/2.0.0-dev/index.html).

As you can see, you have to use 'replaceOptions' option instead of the 'replace' option you have set into your JSFiddle example.

Another approach could be to store the current selected country into an external variable. Then, when the user click on another country, you can easily reset the background-color of the previous selected country.

**Comment by akashdeepkanojia** [comment]
Thankyou so much. I knew it could be implemented with external variable but I wanted to know if there is a built in feature then why use external variable. `replaceOptions` worked perfectly.

**Comment by neveldo** [comment]
You're are welcome. If the performance are good for you, it's ok, but I think that using an external variable is a more efficient way in your case as only two areas will be updated on a click. Using replaceOptions implies to update all the area/plots/links added on the map, so it can be a little slower.

**Comment by akashdeepkanojia** [comment]
Thanks. Got your point. But I just realized that the `update` with single area is still slower than the `mouseenter` / `hover` animation. That is really smooth so using that with multiple areas. I'm now toggling `mouseenter`/`mouseleave` on click.

**Comment by neveldo** [comment]
Hello @akashdeepkanojia , Thank you for having shared your solution !
