### ISSUE TITLE
Is it possible to align/arrange legend elements?

### ISSUE THREAD

**Issue by samerafach** [neveldo/jQuery-Mapael#240]
I have a Mapael with 6 legend items. I would like to manage the space there, and not have them either all horizontal or vertical. I would like to have them arranged as 2x3 array/table. Is that possible?

**Comment by neveldo** [comment]
Hello @samerafach ,

Unfortunately, Mapael doesn't allows this kind of sort for the legend items for now, only vertical and horizontal sorting are available. However, I think it could be a great feature to add in the future ! 

Feel free to make a pull request for it if you want to give a hand :)

**Comment by chrislo2401** [comment]
Hi Vincent, thanks for this great plugin.

I also need to create a legend that has a very customised design, so I'm creating a custom legend instead of using the built in legend functionality.

To highlight the corresponding area when a legend item is clicked on, I was thinking that I can use the "update" event on the map container and pass in a mapOptions object to update the area (i.e. change the fill colour). Before I start writing too much custom code, are ther any exposed event handlers for the areas that I can use to turn each one on and off? I couldn't see anything in the documentation but wanted to check before I start managing it all myself.

Thanks,
Chris

**Comment by neveldo** [comment]
Hi Chris, you are welcome !

I think your way is the right one for building a custom legend, by listening click events on your legend items and triggering an "update" event on the map container. 

However, I don't understand why you need to set event handlers on the areas ? I think you just have to bind the 'click' event on your legend items and then, trigger an 'update' event to highlight the proper area depending on the clicked item (feel free to add custom option values in the object that contains the definition of your areas in order to identify which area need to by hidden/shown on click). 

Did you check [this example](https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/advanced/update_event_for_refreshing_elements.html) for updating the map ?

**Comment by Indigo744** [comment]
@chrislo2401 do you still need help or is it ok?

@samerafach adding more legend type is a never-ending problem. It is hard to cater for all people. Horizontal and vertical legends are common enough. For custom legend, the best approach would be to create your own and trigger update as needed, as @chrislo2401 explained.
