### ISSUE TITLE
[info] realistic map, possible?

### ISSUE THREAD

**Issue by dnsBlah** [neveldo/jQuery-Mapael#242]
Hi all,

is it possible to generate a more realistic map ?
A little bit... 'google map' like, but use mapael instead ? :)

**Comment by neveldo** [comment]
Hello @dnsBlah ,

As Mapael renders SVG nodes, you will never be able to get as realistic resul as Google Maps or Open Street Map. However, you can improved the level of detail of your map by limiting the simplification of the paths (but the JS file size will increase) when creating it. 
Moreover, you can add some extra SVG nodes for defining lakes and rivers for instance by using the aterInit hook : https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/advanced/afterInit_extend_raphael_paper.html .

Otherwise, maybe a tool like [cartobd](https://cartodb.com/) could be more appropriate in your case ?

Feel free to give a feedback in any case !

**Comment by dnsBlah** [comment]
thanks for the response, i understand it now.
I wasn't really looking for rivers or something, but more like .. landscape overlay, don't want roads etc etc ;-)

Will keep it as it is. Thanks!
