### ISSUE TITLE
how to get attributes of any plot/area ？

### ISSUE THREAD

**Issue by scil** [neveldo/jQuery-Mapael#250]
```
var SIZE=20;

var personMap = $(".person-map").mapael({
  plots:{
    'me':{
      size:SIZE}}
}

...
myButton.click(function(){
  SIZE++;
  personMap.trigger('update', [ {plots:{
     'me':{
        size: SIZE  }
   }} ])
});

```

Is there any way to get the size of plot 'me' at any time ?

**Comment by neveldo** [comment]
Hello @scil ,

Yes you can do it : All the data of a map are stored within a mapael instance that can be accessed from here : `$(".mapcontainer").data('mapael')` since Mapael 2.0.0. To get the current options for a specific plotted point, you can use : `$(".mapcontainer").data('mapael').options.plots['your-plot-id].size`. I will improve the documentation on that point soon.

**Comment by alexc101** [comment]
Hello @neveldo 

Similar to the solution posted here, would it be base click events off this code?

for example,
````
$(".mapcontainer").on("click", function(){
     if ($(".mapcontainer").data('mapael').areas === "FR") {
          do something...
     }
});
````

**Comment by scil** [comment]
Thank you very much!

**Comment by neveldo** [comment]
You're welcome :)
