### ISSUE TITLE
Text content & positionning

### ISSUE THREAD

**Issue by nlemoine** [neveldo/jQuery-Mapael#263]
Hi Vincent, 

On the France DOM-TOM map, some departments (75, 92, 93 ,94) text are not well positioned. See the pen here: http://codepen.io/hellonico/pen/gwLryP

Another related question, I didn't find a way to set the text color (`fill` attribute) without setting it on each area item. They don"t seem to be merged with default `text` attribute from `defaultArea`. 

At last, have you heard of github issue templates? Providing a ready made example for reporters by taking advantage of JS online playgrounds such as codepen, jsfilddle, jsbin, etc. would bring better issue descriptions and easier resolution for you. A quick good example: https://github.com/metafizzy/isotope/issues/new

Cheers

**Comment by neveldo** [comment]
Hi @nlemoine , I'm glad there are Mapael users from Rennes ;)

1/ This is a side effect from having split the departments from Ile-De-France in two  : the regular department, and the "zoomed" one in the top right corner. In fact, the two areas are are part of the same SVG path, that is why the text is automatically centered between the two. I see two possible fixes : 

- Set the position of the texts for these departments manually through the margin option.
- Transform the map in order to split the regular and zoomed departments into two distinct paths. (however, when you will hover the zoomed departments, the regular ones will not be highlighted anymore and vice versa

2 / Do you have an example that show the issue ? Here is an example with Mapael 2.0.0 where a default color for plotted points' texts is set (to #b4b4b4) and it works fine : https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/advanced/dataviz_example.html .

3/ I didn't know this feature, thank for having shared it ! I will add it ASAP for mapael issues :)

**Comment by nlemoine** [comment]
I didn't check your location, that explains why Rennes is used in so many map examples :)

1/ Thanks for the workarounds, I'll test them out. 

2/ See updated pen: http://codepen.io/hellonico/pen/gwLryP

3/ You're welcome!

**Comment by neveldo** [comment]
Hello @nlemoine ,

2 / This is simply because the config key 'defaultArea' should be under 'map' !

**Comment by nlemoine** [comment]
Thanks! And sorry, I should have pay attention.
