### ISSUE TITLE
Is it possible to utilize setElementOpacity on individual areas or plots?

### ISSUE THREAD

**Issue by RoyLee** [neveldo/jQuery-Mapael#267]
I looked over the library and found you can do the following:

```
var opt = {
  animDuration: 500,
  hiddenOpacity: 0.1,
  ranges: {
    area: {
      min: parseInt(0),
      max: parseInt(1)
    }
  }
};
$(".mapcontainer").trigger("showElementsInRange", [opt]);
```

This is a for a specific use case of making elements (area in this case) that have values not in the range to have an opacity of .1. 

I would like to make specific states have a certain opacity. Is there a way to get to the objects of all the shown areas/plots so I can modify their opacity in realtime?

I noticed there is a setElementOpacity method but do not know how to get access to it via the browser developer console or code.

Thanks!

**Comment by neveldo** [comment]
Hello @RoyLee ,

Sorry for my late answer ! I don't understand clearly your issue, but if you want to update area properties through JS, you can do it. You can try it on [this example](https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/basic/legend_areas.html), and run in the console the following code : `$('[data-id="department-53"]').css('opacity', 0.5);` in order to update the opacity of the aea "department-53". However, I recommand you to use the "update" event in order to update areas or plots properties in order to avoid some side effect (for instance, if the user hovers the area, it will reset its original properties).

I hope it will help you, otherwise, feel free to explain more your issue !

**Comment by Indigo744** [comment]
@RoyLee do you still have issue or can we close this?

**Comment by RoyLee** [comment]
@Indigo744 Please close this! Thanks!
