### ISSUE TITLE
Hover over to tooltip and click a link in it. 

### ISSUE THREAD

**Issue by Samjin** [neveldo/jQuery-Mapael#268]
Hi  neveldo. I'd like to add a anchor link inside tooltip and let user hover and click it. Is there a default option to keep showing tooltip? If there isn't an option, what's the best way to implement it from my end?

**Comment by neveldo** [comment]
Hi @Samjin , for now, there is no option to keep showing tooltip when the user move its cursor. The tooltip follows the cursor position. 

Take a look at [this example(https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/advanced/eventHandlers_display_information_about_plotted_cities.html) in which hovering plotted points display a fixed div with some texts  and allow users to click on links. You can implement a similar solution. You can display it depending on the cursor position with a little JS (see setTooltip() function within Mapael code) and add a close button for instance.

I hope it will help you !

**Comment by Samjin** [comment]
It surely does! Thank you for your reply. 
I am currently having difficulty of updating mapOption. 
`$(".map-usa").trigger('update', [{
               //mapOptions: data // doesn't work
                newPlots : data, //works
                animDuration: 500,
                afterUpdate : function () {
                    $(".map-usa").trigger('update', [{   // I have to do another update here so map would updated visually, if mapOptions work, I don't need this callback update anymore.
                        deletePlotKeys: arr,
                        animDuration: 500
                    }]);
                }
            }]`

**Comment by neveldo** [comment]
Is your second issue related to the first one ? Otherwise, it should be better to open a new issue and provide a full sample (on JSFiddle for instance) that highlight your issue.

Did you check this [Mapael example](https://rawgit.com/neveldo/jQuery-Mapael/2.0.0/examples/advanced/update_event_for_refreshing_elements.html) that shows you how to perform a map update ?

mapOptions is for updating options of currently shown areas or plots. deletePotKeys stands for deleting some plots from the map.

**Comment by indigo-sam** [comment]
I have found the issue and its solved. Thank you.

**Comment by yunis91** [comment]
> I have found the issue and its solved. Thank you.

can you tell me how you did show and hide the tooltip on click?
