### ISSUE TITLE
Get X and Y coordinates on click

### ISSUE THREAD

**Issue by cat-labs** [neveldo/jQuery-Mapael#280]
Hi,

I am creating an admin where I want to allow non IT people to add new plots on the map. The idea is to show a map, they can click on it and a plot is added. To achieve this, I need to get the X, Y coordinate of the clicked point.

Do you know how I can achieve this?

**Comment by neveldo** [comment]
Hello,

I have found your usecase interesting so I have added to the repository a new sample that does the trick : https://rawgit.com/neveldo/jQuery-Mapael/master/examples/advanced/add_cities_on_map_by_double_click.html. The key is to use mapPagePositionToXY() function in order to get the proper x,y coordinates in order to position the point on the map. I hope it will help you !

**Comment by cat-labs** [comment]
Awesome! Exactly what I needed :-)

Thanks!

**Comment by neveldo** [comment]
You're welcome, I'm glad it helped you !

**Comment by cat-labs** [comment]
Hi again,

It works fine on mac but on windows pc, it doesn t give the right coordinates. Don't know why it behaves like this...

**Comment by neveldo** [comment]
Hi @cat-labs ,

Sorry for my late answer. Did you proceed your tests with the same code between mac and windows ? I think this more a browsers concern than an operating systems one. Could you specify which browser (and which vesion) do you use on mac and windows ? 

Have you tried another browser under windows ?

**Comment by Indigo744** [comment]
@cat-labs can you please provide more information? It seems to work well with Firefox/Chrome on Windows atm...

**Comment by Indigo744** [comment]
@cat-labs sorry to bother you but we would appreciate to have some feedbacks on your issues
