### ISSUE TITLE
Change map background color by custm country

### ISSUE THREAD

**Issue by rebwar** [neveldo/jQuery-Mapael#283]
is there a way to change background color for some country , i need a property for areas section :
```
areas: {
                    "AF": {
                        "value": "",
                        "attrs": {
                            "href": "#"
                        },
                        "tooltip": {
                            "content": "<span style=\"font-weight:bold;\">Afghanistan<\/span><br \/>"
                        }
                    },
```

**Comment by neveldo** [comment]
Hello,

I think you are looking for the attrs.fill option . You will find more about option here : http://www.vincentbroute.fr/mapael/#api-reference.

Hope it will help you !

**Comment by Indigo744** [comment]
@rebwar do you still need help or can we close this issue?

**Comment by maxime-kouemo** [comment]
Hi, isn't there a way to do this without using any update method? Plus can you please give a code example?

**Comment by neveldo** [comment]
Hi @maxime-kouemo ,

Of course, you can set a background color for each area (country) of your map without using any update method. Here is an exemple in which a specific background-color is set for the area ID "department-21", through the map configuration : https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/basic/zoom_features.html

I hope it will help you !

PS : Please open a new issue instead of answering on a closed one if you need further help.

**Comment by maxime-kouemo** [comment]
Thank you. For the P.S, I'll respect it next time. :)
