### ISSUE TITLE
map does not load

### ISSUE THREAD

**Issue by netoguitar** [neveldo/jQuery-Mapael#289]
I have a svg map that I converted to .js, but it does not load the page. any ideas?

**Comment by neveldo** [comment]
Hello,

Could you provide a JSFiddle sample of your code that highlights the issue ?

Thanks in advance !

**Comment by netoguitar** [comment]
Hello,
Thank you, follow the link 

https://jsfiddle.net/netoguitar/4q1onqx6/

**Comment by neveldo** [comment]
Hello @netoguitar , 

Sorry for my late answer. First, on JSFiddle, if you want to load a resource from Github, you should use rawgit : https://rawgit.com/netoguitar/jQuery-Mapael/master/js/maps/rondonia.js , otherwise, you will get a mimetype error.

Regarding your issue, the map is loading properly, but the paths are not shown in the SVG because their coordinates are wrong. Your map size is 231X194, so all the paths should be under these dimensions. However, when I see the first path for instance, it starts at the coordinates 4624,63969. I think you have a remaining translation in your SVG file that you should remove (through Inkscape for instance). All the raw coordinates from your paths (without transforms) have to be included within the dimensions of the SVG.

**Comment by Indigo744** [comment]
@netoguitar do you still need help or can we close this issue?
