### ISSUE TITLE
Unable to show dynamic tooltip

### ISSUE THREAD

**Issue by Smithangshu** [neveldo/jQuery-Mapael#303]
I am not able to show tooltip by assigning a function on content, that function suppose to use ajax post to retrieve location by using coordination which I would like to show on the tooltip..But its always showing "undefined".

**Comment by neveldo** [comment]
Hello @Smithangshu ,

It occurs because the function should return the content to be displayed in the tooltip synchronously. For now, it's not able to wait for an AJAX response or a promise. You could try by setting 'async' option to false (see http://api.jquery.com/jquery.ajax/), then you should be able to return the content after the $.ajax call, but I think it could lead to some aside effects if your API is slow for instance as it will block the execution of the next instructions until the response.

Another workaround to try could be to clean the tooltip content at the beggining of the function ```$('.mapael .mapTooltip').empty()``` , and the set the new content when you get the response from your AJAX call ```$('.mapael .mapTooltip').html(data)```

**Comment by Smithangshu** [comment]
Thank you the second option is more suitable in my case I think.
