### ISSUE TITLE
Zoom to area by name

### ISSUE THREAD

**Issue by mbeckenbach** [neveldo/jQuery-Mapael#307]
The most important first: this is an awesome library!  And it works within angular2 within a few minutes. thank you a lot.

is there a way to zoom zo an area by the id?

I need to zoom to every country in the world on click and it will not be fun to find all the coordinates and hard code it. :-(

Thanks for any input on this :-)

**Comment by neveldo** [comment]
Hello @mbeckenbach ,

Thanks a lot, I'm glad you appreciate Mapael !

Unfortunately, there is no option to zoom on a country by setting its ID in Mapael for now. But it could be great, so feel free to contribute ! I think you can easily compute the center point of a path with the getBBox() function from Raphael.js (you can take a look at the source code of mapael where it's used). Then, it should be easy to call the built-in zoom functions from Mapael in order to zoom at the center of the path. However, you will have to display different zoom levels depending on small or large contries you want to zoom in I think ...

Otherwise, for now, you have to find an open dataset containing the countries geo coordinates, and use it through Mapael options for your by-country zooming feature. Here is a good starting point : https://developers.google.com/public-data/docs/canonical/countries_csv .

I hope it will help you !

**Comment by mbeckenbach** [comment]
Hi @neveldo 
Thanks for your tip. I found have a working solution on that and want to share it for others here.
Please note that I am using typescript (angular2), but it should be hard to translate my snippet into plain javascript.

First, we need a trick to find an area by it's ISO code and trigger it's click event.
Maybe there is some simpler way for that, but I needed a simple quick and dirty solution to select a country at the world map on behalf of the user.

```typescript
private clickOnAreaById(id: string) {
    $(`*[data-id="${id}"]`).trigger('click');
  }
```

Second for some countries like France we might need to extend the area object as the country still has a colony in south amerika and we want to zoom to the center of france. 

```typescript
FR: { tooltip: { content: '(FR) Frankreich'}, zoom: { level: 30, x: 478, y: 99 } },
```

To extend the area object, you can get the current zoom and position by this:

```typescript
zoom = {
      level: this.mapcontainer.data('mapael').zoomData.zoomLevel,
      x: this.mapcontainer.data('mapael').zoomData.zoomX,
      y: this.mapcontainer.data('mapael').zoomData.zoomY
    }
```

Finally you register a click event to zoom to either the hard coded position in your extended area object, or dynamicly zoom to the center of the clicked area. Please note that in my sample below, I calculate a sizeMetric to define the zoomLevel based on the size of the country. My map is configured to allow zoom up to level 50 as the world is quite big and some countries are very small.

```typescript
click: (e, id, mapElem, textElem) => {
              const area: IWorldArea = this.areas[ id ];
              if (area.zoom) {
                // Area has a zoom property, use it
                this.mapcontainer.trigger('zoom', area.zoom);
              } else {
                // Calculate zoom position
                const mbx = mapElem.getBBox();
                const posX = mbx.x + mbx.width / 2;
                const posY = mbx.y + mbx.height / 2;
                const sizeMetric = Math.round(mbx.height * mbx.width / 100);
                let zoomLevel = 0;
                if (sizeMetric < 50) {
                  zoomLevel = 15;
                }
                if (sizeMetric < 10) {
                  zoomLevel = 25
                }
                if (sizeMetric < 5) {
                  zoomLevel = 35;
                }
                if (sizeMetric < 3) {
                  zoomLevel = 40;
                }
                this.mapcontainer.trigger('zoom', { level: zoomLevel, x: posX, y: posY });
              }
```

**Comment by neveldo** [comment]
Hello @mbeckenbach ,

I'm glad you have found a solution, I think I would have implemented the feature exactly in the same way as you !

Thanks a lot for having shared the solution for the other users :) . I mark the issue as resolved !
