### ISSUE TITLE
Making the default the higher opacity

### ISSUE THREAD

**Issue by mytwocents** [neveldo/jQuery-Mapael#311]
Is there a way to have it so that in the ones that have clickable legends, the map loads with the plotted points near invisible and have them become visible once the legend item is clicked?

So basically a map which starts out with no plotted places so you can click on the legend and it becomes visible?

**Comment by neveldo** [comment]
Hi,

There is no built-in option for now (feel free to contribute !), here is a little workaround : 

1 / Set the 'hideElemsOnClick'.opacity' option to 0 in order to fully hide the points (see doc).
2 / Right after the map initialisation , run `$('.myLegend [data-type="label"]').trigger('click');` (the css class of the container is .plotLegend by default). You can test it on : https://rawgit.com/neveldo/jQuery-Mapael/2.1.0/examples/basic/legend_plotted_cities.html

**Comment by mytwocents** [comment]
Hi!

Thank you so much!! If I had half the smarts you did I'd be more than happy to contribute haha... But if I stumble across a way I absolutely will.

Thanks again! Awesome work!

**Comment by neveldo** [comment]
You're welcome @mytwocents  !

**Comment by Indigo744** [comment]
This is actually already built-in :) 
When you create your legends slices, you can set the initial state.

See the `legend.area.slices[].clicked` or `legend.plot.slices[].clicked` : (Boolean, default : false) Set to true in order to initialize the legend item in the 'clicked' state on the map load.

**Comment by neveldo** [comment]
Wow, you're right @Indigo744 , I forgot about this option ! Sometimes, I wonder if you don't know jQuery Mapael better than me :)

**Comment by Indigo744** [comment]
Ahahah! Don't worry, it's simply because I worked on this very feature ;-)
