### ISSUE TITLE
Changing specific portion of SVG file

### ISSUE THREAD

**Issue by andersonreloaded** [neveldo/jQuery-Mapael#334]
Hi Folks,

Not related to Mapael library, but thought of posting here to get valuable comments.
Working on a project, which requires certain nodes to be displayed on the map and nodes' health is updated periodically and the same needs to be reflected in the icon or symbol being used for representing the node. 

If the node status is binary: ON/OFF, a simple SVG image can be used and the fill attribute can be set to GREEN and RED respectively. In case the node health comprises of multiple states rather than ON/OFF.  For example if the node is ON then it branches to subsequent states such as WEB server is UP/DOWN, DATABASE server UP/DOWN and so on.

Simplest way is to use same icon/SVG with different colors to represent composite status. Rather, I was wondering if there is a mechanism of using a composite SVG image: a rectangle composed of multiple circles, with each circle representing each application and then filling each circle with specific color based on the status.

Regards!

**Comment by Indigo744** [comment]
It's not really easy to understand your needs :-)

1. By "_nodes_", I think you mean "plots".
2. By "_simple SVG image_", I think you mean single-path SVG. 
Mapael already handle single-path SVG for plots, with `plot.type = 'svg'` and `plot.path` options.
However, since this is a single path, only one color can be used.
3. By "_composite SVG image_", I think you mean multiple paths grouped together

Side note: an SVG path can be any vector shape (circle, rectangle, or more complex ones...).

Well, Mapael doesn't support right now using multiple SVG paths to define a plot.
As of now, a plot is a single-entity element.

I don't really see how we could implement this in a simple manner.
@neveldo what do you think?

@andersonreloaded You may need to rethink your approach to the problem. Do you really need to show such subsequent states in the big map? Maybe you can rationalized the states with `ON`/`WARNING`/`OFF` color code (like `GREEN`/`YELLOW`/`RED`). If something is `YELLOW`, then one of the system is `OFF` (like only the web server) and if it's `RED`, then _all_ systems are `OFF`. More information could be added in the tooltip.

**Comment by andersonreloaded** [comment]
@Indigo744: Thanks for your response. Your understanding of my requirements are absolutely correct. You nailed them right! 

I realized that its not simple to implement this at the moment. An approach similar to your suggestion is under implementation.

Regards.

**Comment by neveldo** [comment]
Hi @andersonreloaded @Indigo744 ,

I agree with the proposal from @Indigo744 in which the details are shown in the tooltips. For now, as @Indigo744, I don't see how to implement this feature simply as it requires to deal with multiple paths and it I think it will be tricky to position them properly on them map, highlight them together on mouseover, handle transforms, etc. However, it could be a good candidate for an extension :)

We could check if Raphael.js does handle SVG group, which could be a good approach. I saw that it provides a ["set" feature](http://dmitrybaranovskiy.github.io/raphael/reference.html#Paper.set) but I don't know if it could help us.

**Comment by Indigo744** [comment]
Actually the "set" feature is just a glorified array. It does not represent an actual SVG group.
You can apply attributes/transforms/animation on a set, and internally Raphael will simply loop over all elements.

**Comment by neveldo** [comment]
Hmm, that was what I thought at first sight :( . It seems that raphael.js doesn't handle SVG groups.

Maybe we should consider using Snap.svg instead of Raphael for the next major version of Mapael (Snap.svg is the raphael.js but for modern browsers, by the same author). It seems to handle SVG groups well : http://snapsvg.io/docs/#Paper.g . 

(off topic, but I was also thinking for the next major about the feasability of getting rid of jquery, as most of the jQuery feature can be rewritten in vanillaJS I think)

**Comment by Indigo744** [comment]
@neveldo I think we should discuss this in specific topic if you don't mind. I'll start one ASAP ;-)

Regarding this issue, it seems hard to implement properly and it is quite specific for your need. I will close this for now. @andersonreloaded if you need more help, please reopen this issue or open a new one.
