### ISSUE TITLE
Purpose of computing plotOffsetX/plotOffsetY in updateElem

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#339]
@neveldo 

I can't seem to understand the need behind the plotOffsetX/plotOffsetY computation of the `updateElem()` function. The `elem.mapElem.getBBox()` should already have the proper data. Why adding/removing an offset?

https://github.com/neveldo/jQuery-Mapael/blob/d5c1d6e751159b096b4b2a322bb4e8f9955ed27e/js/jquery.mapael.js#L1406-L1418

**Comment by neveldo** [comment]
I think mapElemBBox is just a fake "bbox" object that contains the values of the bbox of the map element that it will take after the update, in order to compute properly the text coordinates within the later self.getTextPosition() call. Indeed, getTextPosition() have to take the bbox with the future coordinates of the element, not the current ones.

elemOptions contain the future size of the element (that is potentially different from the initial size), whereas mapElemBBox to contain the current bbox of the plot (that is updated a few lines later through the self.animate() call).

**Comment by Indigo744** [comment]
Indeed, i understand. Thanks for the explanation :)
