### ISSUE TITLE
Raphael getBBox

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#340]
@neveldo 

I recently created the function `getBBoxWithCenter()` which get the Boundary Box of an element, and add its center coordinates cx, cy.

However, I noticed that this information is already here!

With Raphael 2.2.7 (latest) : http://jsfiddle.net/can4e7q0/1/
`element.getBBox()` will return the following object:
```
 { x, y, x2, y2, width, height, cx, cy, toString }
```
However, if I go back to Raphael 2.1.0, jsfiddle.net/can4e7q0/1 it will return the following object:
```
 { x, y, x2, y2, width, height, toString }
```

Indeed, after looking through Raphael commits, I found this one: https://github.com/DmitryBaranovskiy/raphael/commit/2dd068a94c123ff10deb930aa48d279896b45864

So, my question is: should we ditch the internal function and use the getBBox which give all we need? However, I fear some people are using older version of Raphael and thus may encounter issues. 

In `package.json`, we ask for a minimum of Raphael 2.1.0. If we bump it to 2.1.1, we can get the complete BBox values.

Or we can keep the internal function and check if cx/cy are defined and add them if needed.

What do you think?

**Comment by neveldo** [comment]
Hi @Indigo744 ,

Great discovery, I wasn't aware that Raphael.js was providing these informations since such a long time !

For my part, I'm definitely in favor of switching the minimum version of Raphael to 2.1.1 in order to get these data directly from the library instead of computing them in Mapael. But I think it should come with the release of a new major version of Mapael, following the semver principles, as it will lead to a non backward compatible change for the users if they don't upgrade Raphael.js along with Mapael.

What is your point of view ?

**Comment by Indigo744** [comment]
I would favor bumping the minimum Raphael version as well, since it's not _that_ big.

Actually, this is not a breaking change, since until recently we asked for Raphael 2.2.0. And PR #329 authorized the use of 2.1.0 as well (for older IE).

So we could just update it to authorize 2.1.1.
Also, even the [README.md](https://github.com/neveldo/jQuery-Mapael/blob/master/README.md) suggest [2.1.2 for older version](https://github.com/neveldo/jQuery-Mapael/blame/master/README.md#L18).

**Comment by neveldo** [comment]
My bad, you are right  ! Thanks for having updated the roadmap !
