### ISSUE TITLE
Change background of area with plotted points.

### ISSUE THREAD

**Issue by ankitdholakiya** [neveldo/jQuery-Mapael#364]
I have a dynamic plots coming from the databse. with the values x and y points. I am setting them up successfully. The main thing is I want to change the areas which have the plots added dynamically.

I can not find an exact method to get this area where plots belongs.

Can you please provide me any example of that?

**Comment by neveldo** [comment]
Hello,

I think the simplest way would be to retrieve that information from your DB if you can (maybe you store the related country / county for a city ?).

Otherwise, relying only on mapael, I think it will be tricker. Here is a solution I'm thinking about : 

1 - After the map initialisation, loop on all the created areas (accessible through `$('.mapcontainer').data('mapael').areas;` under the 'mapElem' key. Call `getBBox()` on all the areas in order to get the x1,y1, x2, y2 of the boundary box of the areas , and store them in a new object.

2 - When adding a city, get its (x,y)  coordinates from its latitude, longitude `$('.mapcontainer').data('mapael').mapConf.getCoords(lat, long)` . Check the (x, y) city coordinates with your object that stores the bbox infos to get the related area ID.

I hope it will help you !

**Comment by ankitdholakiya** [comment]
Let me try and get back to you.

**Comment by ankitdholakiya** [comment]
I resolved this issue by getting the area ID and saving it to the database, I tried to get coords but that's the buggy solution. You will not get 100% solution.
Here is the code I used:

 `, defaultArea: {

                attrs: {
                    fill: "#FFFFFF"
                   , stroke: "#0081c6",
                    "stroke-width": 1
                },
                attrsHover: {
                    fill: "#FFFFFF"
                   , stroke: "#0081c6",
                    "stroke-width": 3
                },
                eventHandlers: {
                    click: function (e, id, mapElem, textElem, elemOptions) {
                        debugger;
                        selectedArea = id;
                    }
                }
            }`

You will have the **selectedArea** you can use it to save in database.

**Comment by neveldo** [comment]
Hello,

Great, I'm glad you found a workaround ! After some thoughts, it seems that you are right , the "bbox" solution I have first provided is not appropriate at all to find the related area of a city ! I think I was a little tired, sorry for the bad solution ...

Your solution seems based on the 'click' event to be ok, thanks for having posted the solution for your case :)
