### ISSUE TITLE
world map with mercator projection

### ISSUE THREAD

**Issue by yingban** [neveldo/jQuery-Mapael#37]
Hi neveldo,

great work ! 
Is there any parameter to change the projection style ? or should i create my own map ?

Thanks

**Comment by cgordenne** [comment]
Hello,

I'm using a mercator projection map too. I have only one problem, the getCoords() method.
Do you have an example for this type of projection ?

**Comment by neveldo** [comment]
Hello,

Unfortunately, for now, there is no example of maps for mapael with a mercator projection.

Maybe you could find useful information in this thread from stackoverflow : http://stackoverflow.com/questions/14329691/covert-latitude-longitude-point-to-a-pixels-x-y-on-mercator-projection .

Feel free to share your feedback about mercator projection here !

**Comment by scooterlord** [comment]
Hello, it was not until today that I realized I needed a mercator projection too. Are there any plans for implementing this on mapael?

**Comment by neveldo** [comment]
Hello,

As the getCoords() function just takes as parameters a couple of latitude,longitude and returns a couple of x,y coordinates, there is no need of implementing a specific projection in mapael. The algorithm that allows to convert a (latitude,longitude) into a (x,y) should fit within this function.

I think the tutorial for creating new maps (http://www.vincentbroute.fr/mapael/create-map.php#getcoords) should be completed in order to show how to handle maps with mercator projection. I will add it to my todos, but feel free to contribute if you have any time !

**Comment by scooterlord** [comment]
Thanks for your pointers. I wish I was fluent enough with js that I could help out :/

**Comment by Indigo744** [comment]
Dear all,
We are working on an example for Mercator projections.
Could you provide us your Mercator map? I have trouble finding a *good* one... :-/
Thanks a lot.

**Comment by Indigo744** [comment]
As the Mercator projection is now fully implemented, we will close this issue.

Feel free to open a new thread if you have any questions.
