### ISSUE TITLE
Multiple tooltip

### ISSUE THREAD

**Issue by dannymaulana234** [neveldo/jQuery-Mapael#50]
Hello , I have downloaded and tried, this is great jQuery maps.
How to create multiple tooltip with different class based on country, e.g. France (".mapTooltip-2"), Germany (".mapTooltip-3"). 
I tried below code but not work:

plots : {
  'france' : {
	latitude :48.86, 
	longitude :2.3444, 
	tooltip: {
		cssClass : "mapTooltip-2",
	        content : "FRANCE"
	}
}

Appriciate any help, thanks in advance.

**Comment by neveldo** [comment]
Hello,

You pointed out a lack in mapael : for now, it's not possible to associate
a different class for each tooltip.

However, you can do this by adding an "event handler" that bind the
mouseenter event in order to set a custom css class to the tooltip div.
Here is a working example :  http://jsfiddle.net/neveldo/jz6uhtme/ , you
can try it on the green areas. I bound the mouseenter event in order to add
a custom css class defined in the options for each areas.

I hope this will help you !

2015-04-02 12:08 GMT+02:00 dannymaulana <notifications@github.com>:

**Comment by Indigo744** [comment]
@dannymaulana234: FYI, what you asked is possible in [Mapael 1.1.0](https://github.com/neveldo/jQuery-Mapael/releases/tag/1.1.0) (released on August 31th). 
> The new option 'cssClass' allows to set additional CSS class(es) the tooltip for a specific area or a plotted point
