### ISSUE TITLE
Animate zoom

### ISSUE THREAD

**Issue by nlemoine** [neveldo/jQuery-Mapael#52]
Hi, 

Is there any way ton animate zoom when clicking on an area?

Thanks !

**Comment by neveldo** [comment]
Hello,

I think you took a look at this example in order to zoom on a specific area :  http://jsfiddle.net/neveldo/ejf9dsL9/ . For now, there is no way to animate the zoom when clicking on an area, but I think this could be an useful feature for mapael, I will add it to my todo. Feel free to contribute if you can, there is maybe an answer for adding this feature to mapael here : https://groups.google.com/forum/?fromgroups#!topic/raphaeljs/7eA9xq4enDo .

**Comment by neveldo** [comment]
Hi,

It's done : https://github.com/neveldo/jQuery-Mapael/commit/5607d66c086fd40991413d2f43eaa2935af166fe , it will be released in the next version !

**Comment by nlemoine** [comment]
This is great! Thanks for considering my request.
