### ISSUE TITLE
legend plots as radio buttons

### ISSUE THREAD

**Issue by esauli** [neveldo/jQuery-Mapael#65]
Hi,
I would like to make legend plots functioning as radio buttons rather than check-boxes. By that means: only one legend item is active at a time. Where should I look in the js library to make this happen as I know that its not implemented as a feature itself.

thanks

ps. my project is http://opendatamonitor.eu/ , there are many performance and responsive issues to be still resolved.

**Comment by neveldo** [comment]
Hi,

Thank for sharing your project, I found it very interesting !

I think it should be pretty easy to evolve Mapael in order to get a "radio button" like behaviour for the legend items. I will add a new "exclusive" option in the legend, and a new "hidden" option in order to hide the slices on the map load.

If you are able to wait until a few hours / days for adding this new feature, I will come back to you as soon as it will be done ;)

**Comment by esauli** [comment]
Well I have plenty new features that I am working on so no problem. Thanks and looking forward hearing from you.

**Comment by neveldo** [comment]
Here we go : https://github.com/neveldo/jQuery-Mapael/commit/d7a8ba46314d7e4aa11df79ff468b319f45f1447 , example : http://jsfiddle.net/neveldo/okjwhm1k/ .

I hope this will help you !

**Comment by esauli** [comment]
Thanks a lot. I will credit your work during the how-to tutorials.
Keep up the good work.
Ejona
