### ISSUE TITLE
update trigger new plots 

### ISSUE THREAD

**Issue by airbase9018** [neveldo/jQuery-Mapael#66]
Just tried the package. Very nice btw.

I have problem updating the newly added plots when doing trigger update. 

I followed http://jsfiddle.net/neveldo/TKUy4/ when adding new plots and updating, but when I want to update the new added plot it seems it is not working.

Hope you can enlighten me. :)

**Comment by neveldo** [comment]
Hello,

I'm glad you appreciate mapael.

Here is a minimal working JSFiddle example where a new added plot is then updated (you have to click on "Updated elements" then on "Update elements2" : http://jsfiddle.net/neveldo/98xqw02n

Does it help you ? Otherwise, could you provide a code example that show the issue ?

**Comment by Indigo744** [comment]
@airbase9018 are you still experiencing the problem? 
If not, can you close it? Thanks :)

**Comment by airbase9018** [comment]
sorry forgot about this. should be ok now. thanks. :)
