### ISSUE TITLE
View Box Issue

### ISSUE THREAD

**Issue by shahzadasaeed** [neveldo/jQuery-Mapael#69]
Dear Neveldo,

I am using this map and make Balochistan Pakistan map.. i am facing a problem that is ViewBox is not showing Correctly coordinates.

i am sharing a link please have look
http://icethreads.com/map/

When i plot some Coordinates it shows out from map. i generate xy from getCoords() generator due to height and position of the map it show out from map.. .
Kindly help me to solve this ASAP..
Kind Regards
Shahzada saeed

**Comment by neveldo** [comment]
Hello,

You should have a getCoords() function within your map object (http://icethreads.com/map/js/maps/balochistan_districts.js) in order to translate latitude and longitude into x and y coordinates relative to your map.

Have  you followed this tutorial : http://www.vincentbroute.fr/mapael/create-map.php where I explained how to fill the getCoords() function ?

What are the latitude,longitude and x,y of the four points for this step: http://www.vincentbroute.fr/mapael/create-map.php#getcoords ?

**Comment by Indigo744** [comment]
@shahzadasaeed did you manage to solve your problem? If so, can you close this thread? Thanks.

**Comment by Indigo744** [comment]
It's been 1 week. Closing this thread.
