### ISSUE TITLE
Full screen maps

### ISSUE THREAD

**Issue by Giantwannabe** [neveldo/jQuery-Mapael#76]
Hi, thanks for wonderful plugin.

Is it possible to make the map full screen on browser window?

**Comment by neveldo** [comment]
Hello,

Thank you, I'm glad you appreciate Mapael !

Of course, you can make the map full screen : you just have to set a "width : 100%" style on the map container, and it should work.

I hope this wiil help you.

**Comment by Giantwannabe** [comment]
Thank you very much for the solution. Unfortunately, it does not work for me.

I can make it work by setting the SVG’s height to match the viewport’s height (in chrome dev tool).

One more question, I try to use jQuery to select SVG tag but it does not work.
Is it possible to set ID of the SVG file?
So, I can select it and set the height attribute to the SVG file.

**Comment by neveldo** [comment]
Hello,

You can use for example this jQuery selector in order to get the SVG tag : $('.map svg'); . Once you got it, you can set an ID to the SVG tag through jquery if you want so.

Regarding your issue with the full screen view, do you have an online example of your work ? I thin it will be helpful for helping you :)

For your information, by default, Mapael automatically adjusts the SVG width according to the width of its container. The SVG height is set proportionally to this width in order to preserve the map original ratio.

**Comment by Giantwannabe** [comment]
Hi,

Here is the JSFiidle.
https://jsfiddle.net/Giantwannabe/avu3v43s/1/

I want the map to scale to fit browser window, no scrolling.
I'm not familiar with SVG at all.

**Comment by neveldo** [comment]
Hi,

Thank for the JSFidle, I now see what you want to do. Here is a working example with some explanation : http://jsfiddle.net/neveldo/wsL6ny77/ . Does it help you ?

**Comment by Giantwannabe** [comment]
Yes, it works perfectly for me.
I also enable zoom on the map, too.

http://jsfiddle.net/Giantwannabe/q6aq6kc4/1/


Thank you again for your help. I really appreciate it :D

**Comment by neveldo** [comment]
Hello,

You're welcome, I'm glad that your problem is resolved :)

**Comment by neveldo** [comment]
oops, there was a little mistake in the paper.setSize() arguments (for computing the width). I've updated the JSfiddle to fix the error : http://jsfiddle.net/neveldo/wsL6ny77/

**Comment by Giantwannabe** [comment]
It works like a charm. Thank you very much :)
