### ISSUE TITLE
Ability to Centre Map

### ISSUE THREAD

**Issue by bullantmm** [neveldo/jQuery-Mapael#79]
Is there any way to center a map within its SVG using preserveAspectRatio="xMidYMid"?

I have attempted this by setting it on page load however as soon as a zoom event occurs the map returns to preserveAspectRatio="xMinYMin"

Any help appreacited

**Comment by neveldo** [comment]
Hello,

Thank you for using Mapael. Do you have any online example of your map ? I think you should use  Inkscape in order to edit the SVG and center all the paths of your map once and for all.

**Comment by bullantmm** [comment]
Hi. Here is a live preview of the map http://fresh-off-the-plane.com/discover-hong-kong

**Comment by neveldo** [comment]
Hello,

Thanks you for the live preview link. I think you should edit your map SVG source file into Inkscape in order to center it and remove the blank space at the right of the map. (If you haven't kept the SVG, you still can convert the mapael map to SVG format by using this tool : http://www.vincentbroute.fr/mapael/mapael-to-svg.php ).

You can automatically adjust the document size in File > Document properties > Resize page to content. Before that, ensure that “Optimized“ is checked for the “Store transformation” option in "File > Inkscape Preferences > Transforms", and that there is no SVG groups within the XML tree.

After converting your map to the mapael format, you will have to adjust the xOffset within the getCoords() funtion (and maybe the yOffset too).

**Comment by bullantmm** [comment]
I have tried that solution, the issue is that I need the map to be responsive and fill the height of the browser window whilst staying centered. Is there any proper way to for the preserveAspectRatio value to "xMidYMid"?

**Comment by neveldo** [comment]
You can do this, see this JSfiddle example : http://jsfiddle.net/neveldo/wsL6ny77/ (it comes from this issue : https://github.com/neveldo/jQuery-Mapael/issues/76)

**Comment by Indigo744** [comment]
@bullantmm : any update ? 
If your issue is resolve, can you close this thread? 
Thanks a lot :)
