### ISSUE TITLE
MouseOver and unselectable texts

### ISSUE THREAD

**Issue by emilie-t** [neveldo/jQuery-Mapael#83]
First of all, thanks for this great plugin.
On my map, I added some plots. These plots contain texts. Everything works fine.
I added a mouseover action on the plot using the eventHandlers so that the plot would take a dynamically created color. The problem is that when my mouse rolls over the text in the plot, I loose the focus on the mouseover of the plot. Is there a way to make the text unselectable or to stop the propagation of the mouseover ?
Thank you

**Comment by neveldo** [comment]
Hello,

Thank you, I'm glad you appreciate Mapael ! Do you have an online example of your work with mapael or could you post your code ? I think this will be helpful.

I think you should,  in your mouseover callback, update the current background color of the plot and also trigger an 'update' event in order to upate the 'attrsHover' option of the plot with the same color (in order to have the correct behaviour when your mouse rolls over the text in the plot).

**Comment by emilie-t** [comment]
Here is my online example : http://jsfiddle.net/emiliet/xc8p3g2s/11/
The idea is to swap the colors of the plots and the colors of the areas related to it, on the mouseover.

**Comment by emilie-t** [comment]
Here is an example online of what I'd like to do :
http://jsfiddle.net/emiliet/xc8p3g2s/13/
The idea is to swap the colors of the plots with the colors of the areas related to plots, on the mouseover.

**Comment by neveldo** [comment]
I think you should overwrite $.fn.mapael.setHover() function in order to set your own behaviour on plot / areas over. Here is a (quick) working example I made from your JSFiddle : http://jsfiddle.net/neveldo/ykz97c1v/ . Does it help you ?

**Comment by emilie-t** [comment]
Brilliant!
It helps a lot!!!
Merci beaucoup Vincent.

**Comment by neveldo** [comment]
De rien, content de vous avoir aidé !
