### ISSUE TITLE
Legends: min/max options for slice is inclusive/exclusive

### ISSUE THREAD

**Issue by Indigo744** [neveldo/jQuery-Mapael#84]
We can specify slices for the legends using `legend.area.slices[].min` and `legend.area.slices[].max`.

The documentation says:
```
min : (Float) The minimal value for the interval defining the slice
max : (Float) The maximal value for the interval defining the slice
```

However, it is never said whether the min or max value is inclusive or exclusive.

After looking at the code, it seems that the `min` is **inclusive**, and the `max` is **exclusive**.
Line 1068 & 1069:
```
&& (typeof sliceOptions.min == "undefined" || elemValue >= sliceOptions.min)
&& (typeof sliceOptions.max == "undefined" || elemValue < sliceOptions.max))
```

I wonder if this is the best approach, as I was expecting both values to be inclusive. After all, when you define a maximum value, it is usually inclusive. But I don't really expect you to change it since it would broke a lot of legends.

In any way, you should explicitly tell in your doc if this is exclusive/inclusive.

**Comment by neveldo** [comment]
Hello,

For your information, there is also a similar piece of code in the Mapael.getLegendSlice() function in order to overload elements display options with the display options of the matching legend slice. 

Unfortunately, I don't remember why I made the 'max' value exclusive, it comes from the very first version of Mapael ... I also think it should be inclusive, otherwise an area associated with the maximum possible value will not be handled properly by a legend slice.

I will add it to my todo (or feel free to made a PR), in order to check potential side effects. For a v2.0.0 we can authorise ourself to break the backward compatiblity, but at worst, some plots or areas will be assigned to the lower slice instead (those which have a value that matches the max value of a slice and the max value of the upper slice).
